// IPL 2026 Match Schedule - Auto-updated by daily_update.py
// Last updated: 2026-05-03 09:50:06

const iplMatches = {
    matches: [
        {
                "id": 1,
                "matchNumber": 1,
                "date": "2026-03-28",
                "time": "19:30",
                "venue": "M. Chinnaswamy Stadium, Bengaluru",
                "team1": "RCB",
                "team2": "SRH",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "RCB",
                        "margin": "6 wickets",
                        "team1Score": "201/9 (20 ov)",
                        "team2Score": "203/4 (19.3 ov)",
                        "potm": "Jacob Duffy",
                        "potmTeam": "RCB",
                        "summary": "RCB won by 6 wickets"
                }
        },
        {
                "id": 2,
                "matchNumber": 2,
                "date": "2026-03-29",
                "time": "19:30",
                "venue": "Wankhede Stadium, Mumbai",
                "team1": "MI",
                "team2": "KKR",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "MI",
                        "margin": "6 wickets",
                        "team1Score": "220/4 (20 ov)",
                        "team2Score": "224/4 (19.4 ov)",
                        "potm": "Shardul Thakur",
                        "potmTeam": "MI",
                        "summary": "MI won by 6 wickets"
                }
        },
        {
                "id": 3,
                "matchNumber": 3,
                "date": "2026-03-30",
                "time": "19:30",
                "venue": "Barsapara Cricket Stadium, Guwahati",
                "team1": "RR",
                "team2": "CSK",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "RR",
                        "margin": "8 wickets",
                        "team1Score": "127 (19.2 ov)",
                        "team2Score": "128/2 (14.5 ov)",
                        "potm": "Nandre Burger",
                        "potmTeam": "RR",
                        "summary": "RR won by 8 wickets"
                }
        },
        {
                "id": 4,
                "matchNumber": 4,
                "date": "2026-03-31",
                "time": "19:30",
                "venue": "Maharaja Yadavindra Singh Stadium, New Chandigarh",
                "team1": "PBKS",
                "team2": "GT",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "PBKS",
                        "margin": "3 wickets",
                        "team1Score": "162/6 (20 ov)",
                        "team2Score": "165/7 (19.4 ov)",
                        "potm": "Cooper Connolly",
                        "potmTeam": "PBKS",
                        "summary": "PBKS won by 3 wickets"
                }
        },
        {
                "id": 5,
                "matchNumber": 5,
                "date": "2026-04-01",
                "time": "19:30",
                "venue": "BRSABV Ekana Cricket Stadium, Lucknow",
                "team1": "LSG",
                "team2": "DC",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "DC",
                        "margin": "6 wickets",
                        "team1Score": "141 (18.5 ov)",
                        "team2Score": "145/4 (17.1 ov)",
                        "potm": "Sameer Rizvi",
                        "potmTeam": "DC",
                        "summary": "DC won by 6 wickets"
                }
        },
        {
                "id": 6,
                "matchNumber": 6,
                "date": "2026-04-02",
                "time": "19:30",
                "venue": "Eden Gardens, Kolkata",
                "team1": "KKR",
                "team2": "SRH",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "SRH",
                        "margin": "65 runs",
                        "team1Score": "226/8 (20 ov)",
                        "team2Score": "161 (16 ov)",
                        "potm": "Nitish Kumar Reddy",
                        "potmTeam": "SRH",
                        "summary": "SRH won by 65 runs"
                }
        },
        {
                "id": 7,
                "matchNumber": 7,
                "date": "2026-04-03",
                "time": "19:30",
                "venue": "MA Chidambaram Stadium, Chennai",
                "team1": "CSK",
                "team2": "PBKS",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "PBKS",
                        "margin": "5 wickets",
                        "team1Score": "209/5 (20 ov)",
                        "team2Score": "210/5 (19.3 ov)",
                        "potm": "Priyansh Arya",
                        "potmTeam": "PBKS",
                        "summary": "PBKS won by 5 wickets"
                }
        },
        {
                "id": 8,
                "matchNumber": 8,
                "date": "2026-04-04",
                "time": "15:30",
                "venue": "Arun Jaitley Stadium, Delhi",
                "team1": "DC",
                "team2": "MI",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "DC",
                        "margin": "6 wickets",
                        "team1Score": "162/6 (20 ov)",
                        "team2Score": "164/4 (18.2 ov)",
                        "potm": "Sameer Rizvi",
                        "potmTeam": "DC",
                        "summary": "DC won by 6 wickets"
                }
        },
        {
                "id": 9,
                "matchNumber": 9,
                "date": "2026-04-04",
                "time": "19:30",
                "venue": "Narendra Modi Stadium, Ahmedabad",
                "team1": "GT",
                "team2": "RR",
                "status": "completed",
                "category": "league",
                "result": {
                        "winner": "RR",
                        "margin": "6 runs",
                        "team1Score": "210/6 (20 ov)",
                        "team2Score": "204/8 (20 ov)",
                        "potm": "Ravi Bishnoi",
                        "potmTeam": "RR",
                        "summary": "RR won by 6 runs"
                }
        },
        {
                "id": 10,
                "matchNumber": 10,
                "date": "2026-04-05",
                "time": "15:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "LSG",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 11,
                "matchNumber": 11,
                "date": "2026-04-05",
                "time": "19:30",
                "venue": "M. Chinnaswamy Stadium, Bengaluru",
                "team1": "RCB",
                "team2": "RR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 12,
                "matchNumber": 12,
                "date": "2026-04-06",
                "time": "19:30",
                "venue": "Eden Gardens, Kolkata",
                "team1": "KKR",
                "team2": "PBKS",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 13,
                "matchNumber": 13,
                "date": "2026-04-07",
                "time": "19:30",
                "venue": "Barsapara Cricket Stadium, Guwahati",
                "team1": "RR",
                "team2": "MI",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 14,
                "matchNumber": 14,
                "date": "2026-04-08",
                "time": "19:30",
                "venue": "Arun Jaitley Stadium, Delhi",
                "team1": "DC",
                "team2": "GT",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 15,
                "matchNumber": 15,
                "date": "2026-04-09",
                "time": "19:30",
                "venue": "Eden Gardens, Kolkata",
                "team1": "KKR",
                "team2": "LSG",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 16,
                "matchNumber": 16,
                "date": "2026-04-10",
                "time": "19:30",
                "venue": "Barsapara Cricket Stadium, Guwahati",
                "team1": "RR",
                "team2": "RCB",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 17,
                "matchNumber": 17,
                "date": "2026-04-11",
                "time": "15:30",
                "venue": "Maharaja Yadavindra Singh Stadium, New Chandigarh",
                "team1": "PBKS",
                "team2": "SRH",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 18,
                "matchNumber": 18,
                "date": "2026-04-11",
                "time": "19:30",
                "venue": "MA Chidambaram Stadium, Chennai",
                "team1": "CSK",
                "team2": "DC",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 19,
                "matchNumber": 19,
                "date": "2026-04-12",
                "time": "15:30",
                "venue": "BRSABV Ekana Cricket Stadium, Lucknow",
                "team1": "LSG",
                "team2": "GT",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 20,
                "matchNumber": 20,
                "date": "2026-04-12",
                "time": "19:30",
                "venue": "Wankhede Stadium, Mumbai",
                "team1": "MI",
                "team2": "RCB",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 21,
                "matchNumber": 21,
                "date": "2026-04-13",
                "time": "19:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "RR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 22,
                "matchNumber": 22,
                "date": "2026-04-14",
                "time": "19:30",
                "venue": "MA Chidambaram Stadium, Chennai",
                "team1": "CSK",
                "team2": "KKR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 23,
                "matchNumber": 23,
                "date": "2026-04-15",
                "time": "19:30",
                "venue": "M. Chinnaswamy Stadium, Bengaluru",
                "team1": "RCB",
                "team2": "LSG",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 24,
                "matchNumber": 24,
                "date": "2026-04-16",
                "time": "19:30",
                "venue": "Wankhede Stadium, Mumbai",
                "team1": "MI",
                "team2": "PBKS",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 25,
                "matchNumber": 25,
                "date": "2026-04-17",
                "time": "19:30",
                "venue": "Narendra Modi Stadium, Ahmedabad",
                "team1": "GT",
                "team2": "KKR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 26,
                "matchNumber": 26,
                "date": "2026-04-18",
                "time": "15:30",
                "venue": "M. Chinnaswamy Stadium, Bengaluru",
                "team1": "RCB",
                "team2": "DC",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 27,
                "matchNumber": 27,
                "date": "2026-04-18",
                "time": "19:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "CSK",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 28,
                "matchNumber": 28,
                "date": "2026-04-19",
                "time": "15:30",
                "venue": "Eden Gardens, Kolkata",
                "team1": "KKR",
                "team2": "RR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 29,
                "matchNumber": 29,
                "date": "2026-04-19",
                "time": "19:30",
                "venue": "Maharaja Yadavindra Singh Stadium, New Chandigarh",
                "team1": "PBKS",
                "team2": "LSG",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 30,
                "matchNumber": 30,
                "date": "2026-04-20",
                "time": "19:30",
                "venue": "Narendra Modi Stadium, Ahmedabad",
                "team1": "GT",
                "team2": "MI",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 31,
                "matchNumber": 31,
                "date": "2026-04-21",
                "time": "19:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "DC",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 32,
                "matchNumber": 32,
                "date": "2026-04-22",
                "time": "19:30",
                "venue": "BRSABV Ekana Cricket Stadium, Lucknow",
                "team1": "LSG",
                "team2": "RR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 33,
                "matchNumber": 33,
                "date": "2026-04-23",
                "time": "19:30",
                "venue": "Wankhede Stadium, Mumbai",
                "team1": "MI",
                "team2": "CSK",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 34,
                "matchNumber": 34,
                "date": "2026-04-24",
                "time": "19:30",
                "venue": "M. Chinnaswamy Stadium, Bengaluru",
                "team1": "RCB",
                "team2": "GT",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 35,
                "matchNumber": 35,
                "date": "2026-04-25",
                "time": "15:30",
                "venue": "Arun Jaitley Stadium, Delhi",
                "team1": "DC",
                "team2": "KKR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 36,
                "matchNumber": 36,
                "date": "2026-04-25",
                "time": "19:30",
                "venue": "Sawai Mansingh Stadium, Jaipur",
                "team1": "RR",
                "team2": "PBKS",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 37,
                "matchNumber": 37,
                "date": "2026-04-26",
                "time": "19:30",
                "venue": "Narendra Modi Stadium, Ahmedabad",
                "team1": "GT",
                "team2": "CSK",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 38,
                "matchNumber": 38,
                "date": "2026-04-26",
                "time": "19:30",
                "venue": "BRSABV Ekana Cricket Stadium, Lucknow",
                "team1": "LSG",
                "team2": "KKR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 39,
                "matchNumber": 39,
                "date": "2026-04-27",
                "time": "19:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "MI",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 40,
                "matchNumber": 40,
                "date": "2026-04-28",
                "time": "19:30",
                "venue": "Arun Jaitley Stadium, Delhi",
                "team1": "DC",
                "team2": "RR",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 41,
                "matchNumber": 41,
                "date": "2026-04-29",
                "time": "19:30",
                "venue": "MA Chidambaram Stadium, Chennai",
                "team1": "CSK",
                "team2": "RCB",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 42,
                "matchNumber": 42,
                "date": "2026-04-30",
                "time": "19:30",
                "venue": "Narendra Modi Stadium, Ahmedabad",
                "team1": "GT",
                "team2": "RCB",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 43,
                "matchNumber": 43,
                "date": "2026-05-01",
                "time": "19:30",
                "venue": "Eden Gardens, Kolkata",
                "team1": "KKR",
                "team2": "DC",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 44,
                "matchNumber": 44,
                "date": "2026-05-02",
                "time": "19:30",
                "venue": "MA Chidambaram Stadium, Chennai",
                "team1": "CSK",
                "team2": "MI",
                "status": "completed",
                "category": "league"
        },
        {
                "id": 45,
                "matchNumber": 45,
                "date": "2026-05-03",
                "time": "15:30",
                "venue": "Maharaja Yadavindra Singh Stadium, New Chandigarh",
                "team1": "PBKS",
                "team2": "RCB",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 46,
                "matchNumber": 46,
                "date": "2026-05-03",
                "time": "19:30",
                "venue": "Sawai Mansingh Stadium, Jaipur",
                "team1": "RR",
                "team2": "GT",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 47,
                "matchNumber": 47,
                "date": "2026-05-04",
                "time": "19:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "KKR",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 48,
                "matchNumber": 48,
                "date": "2026-05-05",
                "time": "19:30",
                "venue": "BRSABV Ekana Cricket Stadium, Lucknow",
                "team1": "LSG",
                "team2": "MI",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 49,
                "matchNumber": 49,
                "date": "2026-05-06",
                "time": "19:30",
                "venue": "Arun Jaitley Stadium, Delhi",
                "team1": "DC",
                "team2": "PBKS",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 50,
                "matchNumber": 50,
                "date": "2026-05-07",
                "time": "19:30",
                "venue": "Narendra Modi Stadium, Ahmedabad",
                "team1": "GT",
                "team2": "SRH",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 51,
                "matchNumber": 51,
                "date": "2026-05-08",
                "time": "19:30",
                "venue": "Eden Gardens, Kolkata",
                "team1": "KKR",
                "team2": "RCB",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 52,
                "matchNumber": 52,
                "date": "2026-05-09",
                "time": "15:30",
                "venue": "Sawai Mansingh Stadium, Jaipur",
                "team1": "RR",
                "team2": "DC",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 53,
                "matchNumber": 53,
                "date": "2026-05-09",
                "time": "19:30",
                "venue": "Wankhede Stadium, Mumbai",
                "team1": "MI",
                "team2": "GT",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 54,
                "matchNumber": 54,
                "date": "2026-05-10",
                "time": "15:30",
                "venue": "MA Chidambaram Stadium, Chennai",
                "team1": "CSK",
                "team2": "LSG",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 55,
                "matchNumber": 55,
                "date": "2026-05-10",
                "time": "19:30",
                "venue": "Shaheed Veer Narayan Singh International Stadium, Raipur",
                "team1": "RCB",
                "team2": "MI",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 56,
                "matchNumber": 56,
                "date": "2026-05-11",
                "time": "19:30",
                "venue": "Maharaja Yadavindra Singh Stadium, New Chandigarh",
                "team1": "PBKS",
                "team2": "KKR",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 57,
                "matchNumber": 57,
                "date": "2026-05-12",
                "time": "19:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "GT",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 58,
                "matchNumber": 58,
                "date": "2026-05-13",
                "time": "19:30",
                "venue": "Sawai Mansingh Stadium, Jaipur",
                "team1": "RR",
                "team2": "LSG",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 59,
                "matchNumber": 59,
                "date": "2026-05-14",
                "time": "19:30",
                "venue": "Arun Jaitley Stadium, Delhi",
                "team1": "DC",
                "team2": "CSK",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 60,
                "matchNumber": 60,
                "date": "2026-05-15",
                "time": "19:30",
                "venue": "Eden Gardens, Kolkata",
                "team1": "KKR",
                "team2": "MI",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 61,
                "matchNumber": 61,
                "date": "2026-05-16",
                "time": "15:30",
                "venue": "M. Chinnaswamy Stadium, Bengaluru",
                "team1": "RCB",
                "team2": "PBKS",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 62,
                "matchNumber": 62,
                "date": "2026-05-16",
                "time": "19:30",
                "venue": "Narendra Modi Stadium, Ahmedabad",
                "team1": "GT",
                "team2": "DC",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 63,
                "matchNumber": 63,
                "date": "2026-05-17",
                "time": "15:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "RCB",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 64,
                "matchNumber": 64,
                "date": "2026-05-17",
                "time": "19:30",
                "venue": "BRSABV Ekana Cricket Stadium, Lucknow",
                "team1": "LSG",
                "team2": "PBKS",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 65,
                "matchNumber": 65,
                "date": "2026-05-18",
                "time": "19:30",
                "venue": "Wankhede Stadium, Mumbai",
                "team1": "MI",
                "team2": "RR",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 66,
                "matchNumber": 66,
                "date": "2026-05-19",
                "time": "19:30",
                "venue": "MA Chidambaram Stadium, Chennai",
                "team1": "CSK",
                "team2": "GT",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 67,
                "matchNumber": 67,
                "date": "2026-05-20",
                "time": "19:30",
                "venue": "Eden Gardens, Kolkata",
                "team1": "KKR",
                "team2": "SRH",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 68,
                "matchNumber": 68,
                "date": "2026-05-21",
                "time": "19:30",
                "venue": "Sawai Mansingh Stadium, Jaipur",
                "team1": "RR",
                "team2": "CSK",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 69,
                "matchNumber": 69,
                "date": "2026-05-22",
                "time": "15:30",
                "venue": "Arun Jaitley Stadium, Delhi",
                "team1": "DC",
                "team2": "LSG",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 70,
                "matchNumber": 70,
                "date": "2026-05-22",
                "time": "19:30",
                "venue": "Narendra Modi Stadium, Ahmedabad",
                "team1": "GT",
                "team2": "PBKS",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 71,
                "matchNumber": 71,
                "date": "2026-05-23",
                "time": "15:30",
                "venue": "Rajiv Gandhi International Cricket Stadium, Hyderabad",
                "team1": "SRH",
                "team2": "PBKS",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 72,
                "matchNumber": 72,
                "date": "2026-05-23",
                "time": "19:30",
                "venue": "Wankhede Stadium, Mumbai",
                "team1": "MI",
                "team2": "DC",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 73,
                "matchNumber": 73,
                "date": "2026-05-24",
                "time": "15:30",
                "venue": "M. Chinnaswamy Stadium, Bengaluru",
                "team1": "RCB",
                "team2": "KKR",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 74,
                "matchNumber": 74,
                "date": "2026-05-24",
                "time": "19:30",
                "venue": "BRSABV Ekana Cricket Stadium, Lucknow",
                "team1": "LSG",
                "team2": "RR",
                "status": "upcoming",
                "category": "league"
        },
        {
                "id": 75,
                "matchNumber": 75,
                "date": "2026-05-26",
                "time": "19:30",
                "venue": "TBA",
                "team1": "TBA",
                "team2": "TBA",
                "status": "upcoming",
                "category": "playoff"
        },
        {
                "id": 76,
                "matchNumber": 76,
                "date": "2026-05-27",
                "time": "19:30",
                "venue": "TBA",
                "team1": "TBA",
                "team2": "TBA",
                "status": "upcoming",
                "category": "playoff"
        },
        {
                "id": 77,
                "matchNumber": 77,
                "date": "2026-05-29",
                "time": "19:30",
                "venue": "TBA",
                "team1": "TBA",
                "team2": "TBA",
                "status": "upcoming",
                "category": "playoff"
        },
        {
                "id": 78,
                "matchNumber": 78,
                "date": "2026-05-31",
                "time": "19:30",
                "venue": "M. Chinnaswamy Stadium, Bengaluru",
                "team1": "TBA",
                "team2": "TBA",
                "status": "upcoming",
                "category": "final"
        }
]
};
